import type { DemoCase } from "./types";

export const missionBayCase: DemoCase = {
  id: "BC-2026-0142",
  project: "Mission Bay Data Center",
  equipmentTag: "P-401",
  equipmentName: "Chilled Water Pump",
  delayDays: 77,
  requiredOnSite: "2026. 8. 28.",
  status: "awaiting_internal_approval",
  progress: 82,
  selectedCandidateId: "candidate-c",
  pipeline: [
    { id: "evidence", label: "Project evidence", detail: "31 requirements", state: "done" },
    { id: "sourcing", label: "Supplier search", detail: "14 products", state: "done" },
    { id: "bim_generation", label: "2D → BIM", detail: "3 candidates", state: "done" },
    { id: "coordination", label: "Coordination", detail: "1 installable", state: "done" },
    { id: "commercial_review", label: "Cost & schedule", detail: "0 delay days", state: "done" },
    { id: "internal_approval", label: "Internal approval", detail: "Your decision", state: "active" },
  ],
  candidates: [
    {
      id: "candidate-a",
      manufacturer: "KSB",
      model: "Etanorm 065-040-250",
      label: "Candidate A",
      status: "rejected",
      arrival: "Aug 17",
      evidenceCoverage: 94,
      requirementsPassed: 31,
      requirementsTotal: 31,
      criticalClashes: 1,
      minorClashes: 0,
      connectorOffsetMm: 180,
      totalInstalledCost: 28500,
      costDelta: 1080,
      scheduleImpactDays: 0,
      reason: "Discharge connector intersects the existing return pipe.",
    },
    {
      id: "candidate-b",
      manufacturer: "Grundfos",
      model: "NB 65-125/142",
      label: "Candidate B",
      status: "rejected",
      arrival: "Aug 18",
      evidenceCoverage: 100,
      requirementsPassed: 31,
      requirementsTotal: 31,
      criticalClashes: 1,
      minorClashes: 1,
      connectorOffsetMm: 40,
      totalInstalledCost: 30120,
      costDelta: 2700,
      scheduleImpactDays: 0,
      reason: "Motor removal clearance overlaps the concrete wall.",
    },
    {
      id: "candidate-c",
      manufacturer: "Armstrong",
      model: "4030 4×3×10",
      label: "Candidate C",
      status: "recommended",
      arrival: "Aug 19",
      evidenceCoverage: 100,
      requirementsPassed: 31,
      requirementsTotal: 31,
      criticalClashes: 0,
      minorClashes: 1,
      connectorOffsetMm: 25,
      totalInstalledCost: 31680,
      costDelta: 4260,
      scheduleImpactDays: 0,
      reason: "Only candidate that preserves access and avoids structural changes.",
    },
  ],
  evidence: [
    {
      id: "flow",
      claim: "Design flow",
      value: "420 gpm",
      source: "M-601 · Equipment Schedule · P-401",
      grade: "A",
      confidence: 1,
    },
    {
      id: "inlet",
      claim: "Inlet connection",
      value: "4 in · FLG",
      source: "Armstrong submittal · sheet 6",
      grade: "A",
      confidence: 0.99,
    },
    {
      id: "clearance",
      claim: "Motor removal clearance",
      value: "915 mm",
      source: "Installation manual · page 18",
      grade: "A",
      confidence: 0.98,
    },
    {
      id: "inventory",
      claim: "Inventory",
      value: "2 units · verified 09:42 PDT",
      source: "Pacific Pump Supply · Quote 7614",
      grade: "B",
      confidence: 1,
    },
  ],
};
