import type { DemoCase } from "./types";

export const missionBayCase: DemoCase = {
  id: "BC-2026-0142",
  project: "Mission Bay Data Center",
  equipmentTag: "P-401",
  equipmentName: "Chilled Water Pump",
  delayDays: 77,
  requiredOnSite: "2026. 8. 28.",
  status: "awaiting_internal_approval",
  progress: 82,
  selectedCandidateId: "candidate-c",
  pipeline: [
    { id: "evidence", label: "Project evidence", detail: "31 requirements", state: "done" },
    { id: "sourcing", label: "Supplier search", detail: "14 products", state: "done" },
    { id: "bim_generation", label: "2D → BIM", detail: "3 candidates", state: "done" },
    { id: "coordination", label: "Coordination", detail: "1 installable", state: "done" },
    { id: "commercial_review", label: "Cost & schedule", detail: "0 delay days", state: "done" },
    { id: "internal_approval", label: "Internal approval", detail: "Your decision", state: "active" },
  ],
  candidates: [
    {
      id: "candidate-a",
      manufacturer: "KSB",
      model: "Etanorm 065-040-250",
      label: "Candidate A",
      supplier: "Western States Pumps",
      quoteReference: "KSB-2418",
      inventory: "4 units",
      verifiedAt: "10:42 PDT",
      shipFrom: "Reno, NV",
      status: "rejected",
      arrival: "Aug 17",
      evidenceCoverage: 94,
      requirementsPassed: 31,
      requirementsTotal: 31,
      criticalClashes: 1,
      minorClashes: 0,
      connectorOffsetMm: 180,
      totalInstalledCost: 28500,
      costDelta: 1080,
      scheduleImpactDays: 0,
      reason: "Discharge connector intersects the existing return pipe.",
    },
    {
      id: "candidate-b",
      manufacturer: "Grundfos",
      model: "NB 65-125/142",
      label: "Candidate B",
      supplier: "Pacific Pump Supply",
      quoteReference: "GNF-9017",
      inventory: "2 units",
      verifiedAt: "10:43 PDT",
      shipFrom: "Sacramento, CA",
      status: "rejected",
      arrival: "Aug 18",
      evidenceCoverage: 100,
      requirementsPassed: 31,
      requirementsTotal: 31,
      criticalClashes: 1,
      minorClashes: 1,
      connectorOffsetMm: 40,
      totalInstalledCost: 30120,
      costDelta: 2700,
      scheduleImpactDays: 0,
      reason: "Motor removal clearance overlaps the concrete wall.",
    },
    {
      id: "candidate-c",
      manufacturer: "Armstrong",
      model: "4030 4×3×10",
      label: "Candidate C",
      supplier: "Pacific Pump Supply",
      quoteReference: "Quote 7614",
      inventory: "2 units",
      verifiedAt: "09:42 PDT",
      shipFrom: "Hayward, CA",
      status: "recommended",
      arrival: "Aug 19",
      evidenceCoverage: 100,
      requirementsPassed: 31,
      requirementsTotal: 31,
      criticalClashes: 0,
      minorClashes: 1,
      connectorOffsetMm: 25,
      totalInstalledCost: 31680,
      costDelta: 4260,
      scheduleImpactDays: 0,
      reason: "Only candidate that preserves access and avoids structural changes.",
    },
  ],
  discoveredAlternatives: [
    {
      id: "alt-01",
      manufacturer: "KSB",
      model: "Etanorm 065-040-250",
      discoverySource: "Approved vendor directory + manufacturer catalog",
      evidence: "Datasheet, curve, supplier quote",
      delivery: "Aug 17",
      stage: "bim_reviewed",
      decision: "Advanced to BIM; rejected by discharge-pipe clash.",
      candidateId: "candidate-a",
    },
    {
      id: "alt-02",
      manufacturer: "Grundfos",
      model: "NB 65-125/142",
      discoverySource: "Distributor portal + manufacturer catalog",
      evidence: "Datasheet, installation manual, quote",
      delivery: "Aug 18",
      stage: "bim_reviewed",
      decision: "Advanced to BIM; rejected by motor-removal clearance.",
      candidateId: "candidate-b",
    },
    {
      id: "alt-03",
      manufacturer: "Armstrong",
      model: "4030 4×3×10",
      discoverySource: "Approved vendor directory + supplier response",
      evidence: "Submittal, certified curve, timestamped quote",
      delivery: "Aug 19",
      stage: "bim_reviewed",
      decision: "Advanced to BIM; installable with a 25 mm spool adjustment.",
      candidateId: "candidate-c",
    },
    {
      id: "alt-04",
      manufacturer: "Bell & Gossett",
      model: "e-1510 4BD",
      discoverySource: "Manufacturer selector",
      evidence: "Catalog and performance curve",
      delivery: "Sep 12",
      stage: "schedule_reject",
      decision: "Technically viable, but arrives after the required-on-site date.",
    },
    {
      id: "alt-05",
      manufacturer: "Taco",
      model: "FI 4013",
      discoverySource: "Distributor catalog",
      evidence: "Catalog only",
      delivery: "Unconfirmed",
      stage: "evidence_reject",
      decision: "No timestamped inventory or binding delivery evidence.",
    },
    {
      id: "alt-06",
      manufacturer: "Aurora",
      model: "3800 Series 4×3×10",
      discoverySource: "Manufacturer catalog",
      evidence: "Datasheet and curve",
      delivery: "Sep 04",
      stage: "schedule_reject",
      decision: "Delivery misses the recovery window by seven days.",
    },
    {
      id: "alt-07",
      manufacturer: "Patterson",
      model: "HSC 4×3×10",
      discoverySource: "Web discovery + manufacturer catalog",
      evidence: "Catalog",
      delivery: "Unconfirmed",
      stage: "technical_reject",
      decision: "Base arrangement exceeds the M-601 housekeeping pad.",
    },
    {
      id: "alt-08",
      manufacturer: "Pentair Fairbanks Nijhuis",
      model: "1590 4×3×10",
      discoverySource: "Approved vendor directory",
      evidence: "Legacy submittal",
      delivery: "Sep 08",
      stage: "technical_reject",
      decision: "Required motor and enclosure configuration is not equivalent.",
    },
    {
      id: "alt-09",
      manufacturer: "Wilo",
      model: "CronoBloc BL 80/170",
      discoverySource: "Manufacturer selector",
      evidence: "Datasheet",
      delivery: "Aug 29",
      stage: "technical_reject",
      decision: "Connection standard conflicts with the project flange requirement.",
    },
    {
      id: "alt-10",
      manufacturer: "Xylem Lowara",
      model: "e-NSC 80-200",
      discoverySource: "Distributor portal",
      evidence: "Datasheet and budget quote",
      delivery: "Aug 31",
      stage: "technical_reject",
      decision: "Selected duty point falls outside the accepted efficiency band.",
    },
    {
      id: "alt-11",
      manufacturer: "Ruhrpumpen",
      model: "SCE 4×3×10",
      discoverySource: "Web discovery",
      evidence: "Product page only",
      delivery: "Unconfirmed",
      stage: "evidence_reject",
      decision: "Missing model-specific curve, dimensions, and supplier confirmation.",
    },
    {
      id: "alt-12",
      manufacturer: "Sulzer",
      model: "SNS 80-200",
      discoverySource: "Manufacturer catalog",
      evidence: "Datasheet",
      delivery: "Sep 16",
      stage: "schedule_reject",
      decision: "Manufacturing lead time cannot protect commissioning.",
    },
    {
      id: "alt-13",
      manufacturer: "Ebara",
      model: "GS 80-200",
      discoverySource: "Distributor catalog",
      evidence: "Catalog and stock indication",
      delivery: "Aug 27",
      stage: "technical_reject",
      decision: "Motor voltage option does not match the 480 V project requirement.",
    },
    {
      id: "alt-14",
      manufacturer: "Peerless",
      model: "8196 4×3×10",
      discoverySource: "Prior project submittal library",
      evidence: "Prior submittal",
      delivery: "Unconfirmed",
      stage: "evidence_reject",
      decision: "Prior-project approval cannot verify current stock or current configuration.",
    },
  ],
  evidence: [
    {
      id: "flow",
      claim: "Design flow",
      value: "420 gpm",
      source: "M-601 · Equipment Schedule · P-401",
      grade: "A",
      confidence: 1,
    },
    {
      id: "inlet",
      claim: "Inlet connection",
      value: "4 in · FLG",
      source: "Armstrong submittal · sheet 6",
      grade: "A",
      confidence: 0.99,
    },
    {
      id: "clearance",
      claim: "Motor removal clearance",
      value: "915 mm",
      source: "Installation manual · page 18",
      grade: "A",
      confidence: 0.98,
    },
    {
      id: "inventory",
      claim: "Inventory",
      value: "2 units · verified 09:42 PDT",
      source: "Pacific Pump Supply · Quote 7614",
      grade: "B",
      confidence: 1,
    },
  ],
};
